#
# This makefile should be included into ARM subarchitecture
#

TEMP_SOURCE_DIRS += $(MACHINE_PATH)/..

SOURCES += nds_arm9_bootstrap_stage1.S \
	nds_tpl_sleep.S \
	nds_tpl_stubs.c \
	tpl_interrupt.S \
	tpl_stacks.S \
	tpl_switch_context.S

#	nds_exception_catch.S \
